Post http://localhost:8000/add/
Content-Type: application/json

{
    "name": "Task 1",
    "completed": false
}



###
post http://localhost:8000/add/
Content-Type: application/json

{
    "name": "Task 1",
    "description": "description"
}



###
get http://localhost:8000/list/


###
get http://localhost:8000/get/1


###
patch http://localhost:8000/update/1/
Content-Type: application/json

{
    "name": "Task 1 (Updated)",
    "description": "new description"
}