# Generated by Django 5.1.7 on 2025-03-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='progress',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
